# To execute this docker-compose yml file use `docker-compose -f docker-compose-v3.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-v3.yml down`
version: "3"
services:
  firefox:
    image: selenium/standalone-firefox:latest
    shm_size: 8gb
    environment: 
      - "SE_NODE_OVERRIDE_MAX_SESSIONS=true"
      - "SE_NODE_MAX_SESSION=4"
    ports:
      - "5900:5900"
      - "7900:7900"
      - "4444:4444"
  agent:
    build: crew/
    environment:
      - OPENAI_API_BASE=${OPENAI_API_BASE}
      - OPENAI_MODEL=${OPENAI_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    links:
      - firefox
    extra_hosts:
      - "host_llm:host-gateway"
    volumes:
      - ./crew/:/app
